# 1. Conexion a la base de datos
El objetivo de esta seccion es entender la estructura de la base de datos antes de cargarla o empezar directo con el analisis

In [1]:
# Importacion de librerias

import sqlite3
import pandas as pd
import numpy as np

DB_PATH = "../data/raw/ecommerce.db"

conn = sqlite3.connect(DB_PATH)

In [2]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';"""

tables = pd.read_sql_query(query, conn)

tables

       name
0  2019-Oct
1  2019-Nov
2  2019-Dec
3  2020-Jan
4  2020-Feb

Inspeccionar la estructura de la tabla 2019-Oct para entender el schema antes de evaluar las otras tablas

In [4]:
query = """
PRAGMA table_info('2019-Oct');"""

oct_schema = pd.read_sql_query(query, conn)

oct_schema

   cid           name    type  notnull dflt_value  pk
0    0          index  BIGINT        0       None   0
1    1     event_time    TEXT        0       None   0
2    2     event_type    TEXT        0       None   0
3    3     product_id  BIGINT        0       None   0
4    4    category_id  BIGINT        0       None   0
5    5  category_code    TEXT        0       None   0
6    6          brand    TEXT        0       None   0
7    7          price   FLOAT        0       None   0
8    8        user_id  BIGINT        0       None   0
9    9   user_session    TEXT        0       None   0

In [5]:
sample_query = """
SELECT *
FROM "2019-Oct"
LIMIT 10;
"""

sample = pd.read_sql_query(sample_query, conn)

sample

,index,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,68,2019-10-01 00:01:46 UTC,view,5843665,1487580005092295511,None,f.o.x,9.44,462033176,a18e0999-61a1-4218-8f8f-61ec1d375361
1,72,2019-10-01 00:01:55 UTC,cart,5868461,1487580013069861041,None,italwax,3.57,514753614,e2fecb2d-22d0-df2c-c661-15da44b3ccf1
2,95,2019-10-01 00:02:50 UTC,view,5877456,1487580006300255120,None,jessnail,122.22,527418424,86e77869-afbc-4dff-9aa2-6b7dd8c90770
3,122,2019-10-01 00:03:41 UTC,view,5649270,1487580013749338323,None,concept,6.19,555448072,b5f72ceb-0730-44de-a932-d16db62390df
4,124,2019-10-01 00:03:44 UTC,view,18082,1487580005411062629,None,cnd,16.03,552006247,2d8f304b-de45-4e59-8f40-50c603843fe5
5,152,2019-10-01 00:04:42 UTC,view,5550686,1487580008145748965,None,NaN,1.11,485644718,4afc450a-3459-46db-89c0-84b73aa0fd64
6,193,2019-10-01 00:06:09 UTC,view,5785144,1487580013950664926,None,runail,11.83,480874420,90e9a50a-2718-42dd-b5e4-a9e3293c2dad
7,203,2019-10-01 00:06:35 UTC,view,5800917,1487580011652186237,None,NaN,28.57,555448260,b81dcb7e-f632-42b5-a71a-f4632fe49b45
8,216,2019-10-01 00:06:42 UTC,view,5875717,1487580013229244601,None,NaN,61.75,534432064,1dcf5e6d-09ac-4a2f-8511-092015f0de2a
9,243,2019-10-01 00:07:34 UTC,cart,5753481,1487580013069861041,None,italwax,2.62,514753614,e2fecb2d-22d0-df2c-c661-15da44b3ccf1

In [6]:
event_query = """
SELECT
    event_type,
    COUNT(*) AS event_count
FROM "2019-Oct"
GROUP BY event_type
ORDER BY event_count DESC;
"""

event_types = pd.read_sql_query(event_query, conn)

event_types

         event_type  event_count
0              view       185417
1              cart       123280
2  remove_from_cart        75297
3          purchase        23931

Comprobacion de todas las tablas

In [7]:
tables = [
    "2019-Oct",
    "2019-Nov",
    "2019-Dec",
    "2020-Jan",
    "2020-Feb"
]

schemas = {}

for table in tables:
    query = f'PRAGMA table_info("{table}");'
    schemas[table] = pd.read_sql_query(query, conn)

schemas

{'2019-Oct':    cid           name    type  notnull dflt_value  pk
 0    0          index  BIGINT        0       None   0
 1    1     event_time    TEXT        0       None   0
 2    2     event_type    TEXT        0       None   0
 3    3     product_id  BIGINT        0       None   0
 4    4    category_id  BIGINT        0       None   0
 5    5  category_code    TEXT        0       None   0
 6    6          brand    TEXT        0       None   0
 7    7          price   FLOAT        0       None   0
 8    8        user_id  BIGINT        0       None   0
 9    9   user_session    TEXT        0       None   0,
 '2019-Nov':    cid           name    type  notnull dflt_value  pk
 0    0          index  BIGINT        0       None   0
 1    1     event_time    TEXT        0       None   0
 2    2     event_type    TEXT        0       None   0
 3    3     product_id  BIGINT        0       None   0
 4    4    category_id  BIGINT        0       None   0
 5    5  category_code    TEXT        0       None   0
 6    6          brand    TEXT        0       None   0
 7    7          price   FLOAT        0       None   0
 8    8        user_id  BIGINT        0       None   0
 9    9   user_session    TEXT        0       None   0,
 '2019-Dec':    cid           name    type  notnull dflt_value  pk
 0    0          index  BIGINT        0       None   0
 1    1     event_time    TEXT        0       None   0
 2    2     event_type    TEXT        0       None   0
 3    3     product_id  BIGINT        0       None   0
 4    4    category_id  BIGINT        0       None   0
 5    5  category_code    TEXT        0       None   0
 6    6          brand    TEXT        0       None   0
 7    7          price   FLOAT        0       None   0
 8    8        user_id  BIGINT        0       None   0
 9    9   user_session    TEXT        0       None   0,
 '2020-Jan':    cid           name    type  notnull dflt_value  pk
 0    0          index  BIGINT        0       None   0
 1    1     event_time    TEXT        0       None   0
 2    2     event_type    TEXT        0       None   0
 3    3     product_id  BIGINT        0       None   0
 4    4    category_id  BIGINT        0       None   0
 5    5  category_code    TEXT        0       None   0
 6    6          brand    TEXT        0       None   0
 7    7          price   FLOAT        0       None   0
 8    8        user_id  BIGINT        0       None   0
 9    9   user_session    TEXT        0       None   0,
 '2020-Feb':    cid           name    type  notnull dflt_value  pk
 0    0          index  BIGINT        0       None   0
 1    1     event_time    TEXT        0       None   0
 2    2     event_type    TEXT        0       None   0
 3    3     product_id  BIGINT        0       None   0
 4    4    category_id  BIGINT        0       None   0
 5    5  category_code    TEXT        0       None   0
 6    6          brand    TEXT        0       None   0
 7    7          price   FLOAT        0       None   0
 8    8        user_id  BIGINT        0       None   0
 9    9   user_session    TEXT        0       None   0}

In [8]:
for table, schema in schemas.items():
    print(f"\n{table}")
    print(schema["name"].tolist())

2019-Oct
['index', 'event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']

2019-Nov
['index', 'event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']

2019-Dec
['index', 'event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']

2020-Jan
['index', 'event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']

2020-Feb
['index', 'event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']

In [9]:
# Cuantos eventos contiene cada tabla 

row_counts = {}

for table in tables:
    query = f'SELECT COUNT(*) AS row_count FROM "{table}";'
    result = pd.read_sql_query(query, conn)
    row_counts[table] = result.loc[0, "row_count"]

row_counts

{'2019-Oct': np.int64(407925),
 '2019-Nov': np.int64(462833),
 '2019-Dec': np.int64(351304),
 '2020-Jan': np.int64(443224),
 '2020-Feb': np.int64(429790)}

In [10]:
table_counts = pd.DataFrame(
    list(row_counts.items()),
    columns=["table", "row_count"]
)

total_rows = table_counts["row_count"].sum()

total_rows

np.int64(2095076)

In [11]:
table_counts

      table  row_count
0  2019-Oct     407925
1  2019-Nov     462833
2  2019-Dec     351304
3  2020-Jan     443224
4  2020-Feb     429790

In [12]:
date_ranges = []

for table in tables:
    query = f"""
    SELECT
        MIN(event_time) AS min_event_time,
        MAX(event_time) AS max_event_time
    FROM "{table}";
    """
    
    result = pd.read_sql_query(query, conn)
    
    date_ranges.append({
        "table": table,
        "min_event_time": result.loc[0, "min_event_time"],
        "max_event_time": result.loc[0, "max_event_time"]
    })

date_ranges = pd.DataFrame(date_ranges)

date_ranges

      table           min_event_time           max_event_time
0  2019-Oct  2019-10-01 00:01:46 UTC  2019-10-31 23:56:54 UTC
1  2019-Nov  2019-11-01 00:04:51 UTC  2019-11-30 23:59:27 UTC
2  2019-Dec  2019-12-01 00:01:02 UTC  2019-12-31 23:59:52 UTC
3  2020-Jan  2020-01-01 00:01:31 UTC  2020-01-31 23:58:26 UTC
4  2020-Feb  2020-02-01 00:01:43 UTC  2020-02-29 23:59:54 UTC